## Example Vagrantfile to quickly spawn a centos 7 VM and configure port forwarding

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  #config.vm.box_version = "1.0.0"
  #config.vm.network "private_network", type: "dhcp"
end
Vagrant.configure("2") do |config|
#jenkins
  config.vm.network "forwarded_port", guest: 8080, host: 8080
#kibana - elasticsearch: http://localhost:9200
  config.vm.network "forwarded_port", guest: 5601, host: 56010
#expressjs http://localhost:3000
  config.vm.network "forwarded_port", guest: 3000, host: 3000
end
